### ISSUE TITLE
Consider linking to the actual test.

### ISSUE THREAD

**Issue by mikewest** [GoogleChrome/wptdashboard#91] opened 2017-08-21 20:00 UTC
It would be great if http://wpt.fyi/cookies/secure/set-from-ws.https.sub.html linked to https://w3c-test.org/cookies/secure/set-from-ws.https.sub.html.

**Comment by gsnedders** [comment] 2017-08-21 20:28
Dupe of #49.

**Closed** 2017-08-26 23:48 UTC
